word="VANKAMADDI DEEKSHITH SAI"
print(word)
#To print first accurance of space in +ve direction
print(word[10])
#To print first accurance of space in -ve direction
print(word[-14])
#To print second accurance of d in +ve direction
print(word[8])
#To print first accurance of i in +ve direction
print(word[9])
#To print third accurance of i in -ve direction
print(word[-1])
#To print first accurance of s in +ve direction
print(word[-3])